In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [12]:
df = pd.read_csv("cars.csv")
df.sample(10)

        brand  km_driven    fuel         owner  selling_price
5173    Honda     100000  Diesel   First Owner         325000
5545   Maruti     170000  Petrol   Third Owner         150000
3587     Ford       2860  Diesel   First Owner         795000
2833    Honda      30000  Petrol   First Owner         850000
2260     Tata     120000  Petrol   First Owner         210000
290   Hyundai      35000  Petrol   First Owner         450000
1982    Force      20000  Diesel   First Owner         910000
5585   Maruti      80000  Diesel  Second Owner         425000
498    Maruti      30000  Diesel   First Owner         700000
7552  Hyundai      83000  Petrol   First Owner         475000

In [14]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [16]:
# onehotencoding using pandas

pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [17]:
# K1 OneHotEncoding

pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [19]:
# OneHotEncoding Using Sklearn

x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=0)
x_train

           brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [24]:
ohe=OneHotEncoder(drop="first",sparse_output=False,dtype=np.int32)
x_train_new=ohe.fit_transform(x_train[['fuel','owner']])
x_test_new=ohe.transform(x_test[["fuel","owner"]])
x_train_new.shape,x_test_new.shape

((6502, 7), (1626, 7))

In [25]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 60000, 0, ..., 0, 0, 0],
       ['Tata', 150000, 1, ..., 0, 0, 1],
       ['Hyundai', 110000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]],
      shape=(6502, 9), dtype=object)

In [28]:
# onehotencoding using top categories

counts=df['brand'].value_counts()
df['brand'].nunique()
threshold=100

repl=counts[counts<=threshold].index

pren=pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

In [29]:
pren.shape

(5, 13)