In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv("covid_toy.csv")
df.sample(10)

    age  gender  fever   cough       city has_covid
96   51  Female  101.0  Strong    Kolkata       Yes
26   19  Female  100.0    Mild    Kolkata       Yes
93   27    Male  100.0    Mild    Kolkata       Yes
52   47  Female  100.0  Strong  Bangalore       Yes
49   44    Male  104.0    Mild     Mumbai        No
15   70    Male  103.0  Strong    Kolkata       Yes
43   22  Female   99.0    Mild  Bangalore       Yes
80   14  Female   99.0    Mild     Mumbai       Yes
38   49  Female  101.0    Mild      Delhi       Yes
18   64  Female   98.0    Mild  Bangalore       Yes

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [6]:
x_train

    age  gender  fever   cough       city
69   73  Female  103.0    Mild      Delhi
37   55    Male  100.0    Mild    Kolkata
94   79    Male    NaN  Strong    Kolkata
34   74    Male  102.0    Mild     Mumbai
62   56  Female  104.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
23   80  Female   98.0    Mild      Delhi
46   19  Female  101.0    Mild     Mumbai
92   82  Female  102.0  Strong    Kolkata
48   66    Male   99.0  Strong  Bangalore
27   33  Female  102.0  Strong      Delhi

[80 rows x 5 columns]

In [8]:
# simple method

si = SimpleImputer()
x_train_fever=si.fit_transform(x_train[["fever"]])
x_test_fever=si.transform(x_test[['fever']])
x_train.fever.shape

(80,)

In [9]:
# ordinalencoding 

oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[["cough"]])
x_test_cough=oe.transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [16]:
# onehotencoding on gender,city

ohe1=OneHotEncoder(drop='first',sparse_output=False)
x_train_gc=ohe1.fit_transform(x_train[['gender','city']])
x_test_gc=ohe1.transform(x_test[['gender','city']])
x_train_gc.shape

(80, 4)

In [18]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [ ]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_gc,x_train_cough),axis=1)
x_train_transformed.shape

(80, 7)

In [24]:
# standard method

from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers=[
        ('tnf1', SimpleImputer(), ['fever']),
        ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
    ],
    remainder='passthrough'
)

train_scaled = transformer.fit_transform(x_train)
test_scaled = transformer.transform(x_test)

print(train_scaled.shape)

(80, 7)

In [25]:
test_scaled.shape

(20, 7)