In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("customer.csv")
df.sample(10)

    age  gender   review education purchased
27   69  Female     Poor        PG        No
26   53  Female     Poor        PG        No
28   48    Male     Poor    School        No
1    68  Female     Poor        UG        No
22   18  Female     Poor        PG       Yes
48   39  Female     Good        UG       Yes
42   30  Female     Good        PG       Yes
36   34  Female     Good        UG       Yes
40   39    Male     Good    School        No
4    16  Female  Average        UG        No

In [4]:
df = df.drop(columns=["age","gender"])
df.sample(10)

     review education purchased
6      Good    School        No
45     Poor        PG       Yes
10     Good        UG       Yes
33     Good        PG       Yes
0   Average    School        No
26     Poor        PG        No
23     Good    School        No
35     Poor    School       Yes
20  Average    School       Yes
14     Poor        PG       Yes

In [9]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["purchased"]),df["purchased"],test_size=0.2,random_state=0)

oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
oe.fit(x_train)
x_train_enc=oe.transform(x_train)
x_train_enc

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [10]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [11]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le.fit(y_train)
y_train_enc=le.transform(y_train)
y_test_enc=le.transform(y_test)

In [12]:
y_train_enc

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [13]:
le.classes_

array(['No', 'Yes'], dtype=object)